version: '3.9'

services:
  db:
    container_name: db
    image: postgres:15.2-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: db
    ports:
      - 5432:5432
    networks:
      - default

  backend:
    container_name: hackathon-backend
    build: 
      context: ./back
      dockerfile: Dockerfile
    volumes:
      - ./back:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - default
    environment:
      - CHOKIDAR_USEPOLLING=true

  frontend:
    container_name: hackathon-frontend
    build: 
      context: ./front
      dockerfile: Dockerfile
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - 5173:5173
    depends_on:
      - backend
    networks:
      - default
    environment:
      - CHOKIDAR_USEPOLLING=true

# networks:
#   default:
#     driver: bridge
