# baseURL
@baseURL = http://localhost:3000

###
# get all consultant
GET {{ baseURL }}/consultant
Content-Type: application/json

###
# get consultant
GET {{ baseURL }}/consultant/1
Content-Type: application/json

###
# create analytics
POST {{ baseURL }}/consultant
Content-Type: application/json

{
  "email" : "lassana11@gmail.fr",
  "metier": "testeeurrrr",
  "secteur": "banquerr",
  "disponibilite": "SIX_MOIS",
  "perimetre": "3 km",
  "competences": ["java", "test"],
  "experiences" : ["experiences 1", "expériences 2"],
  "formations" :  ["Formaton java", "Formation Python"],
  "actuel_entrepriseId" : 1,
  "level": 2,
  "salaire": 3000,
  "user_id": 1
}

###
# update con
PATCH  {{ baseURL }}/consultant/2
Content-Type: application/json

  {
    "id": 1,
    "email" : "lassana11@gmail.fr",
    "metier": "testeeurrrr",
    "secteur": "banquerr",
    "disponibilite": "SIX_MOIS",
    "perimetre": "3 km",
    "competences": ["java", "test"],
    "experiences" : ["experiences 1", "expériences 2"],
    "formations" :  ["Formaton windows", "Formation Python"],
    "actuel_entrepriseId" : 1,
    "level": 2,
    "salaire": 3000,
    "user_id": 2
  }

###
# delete consultant
DELETE {{ baseURL }}/consultant/1

